/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface HealthQueryEngineInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkExists"
      | "confidentialProtocolId"
      | "getEligibilityResult"
      | "insuranceModule"
      | "owner"
      | "registry"
      | "researchRegistry"
      | "runAggregateQuery"
      | "runEligibilityCheck"
      | "setInsuranceModule"
      | "setResearchRegistry"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AggregateQueryCompleted" | "EligibilityChecked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "checkExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEligibilityResult",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "insuranceModule",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "researchRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "runAggregateQuery",
    values: [AddressLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "runEligibilityCheck",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setInsuranceModule",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setResearchRegistry",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEligibilityResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "insuranceModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "researchRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "runAggregateQuery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "runEligibilityCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setInsuranceModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setResearchRegistry",
    data: BytesLike
  ): Result;
}

export namespace AggregateQueryCompletedEvent {
  export type InputTuple = [
    institution: AddressLike,
    queryType: BigNumberish,
    cohortSize: BigNumberish
  ];
  export type OutputTuple = [
    institution: string,
    queryType: bigint,
    cohortSize: bigint
  ];
  export interface OutputObject {
    institution: string;
    queryType: bigint;
    cohortSize: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EligibilityCheckedEvent {
  export type InputTuple = [
    patient: AddressLike,
    provider: AddressLike,
    checkId: BytesLike
  ];
  export type OutputTuple = [
    patient: string,
    provider: string,
    checkId: string
  ];
  export interface OutputObject {
    patient: string;
    provider: string;
    checkId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HealthQueryEngine extends BaseContract {
  connect(runner?: ContractRunner | null): HealthQueryEngine;
  waitForDeployment(): Promise<this>;

  interface: HealthQueryEngineInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkExists: TypedContractMethod<[checkId: BytesLike], [boolean], "view">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getEligibilityResult: TypedContractMethod<
    [checkId: BytesLike],
    [string],
    "view"
  >;

  insuranceModule: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registry: TypedContractMethod<[], [string], "view">;

  researchRegistry: TypedContractMethod<[], [string], "view">;

  runAggregateQuery: TypedContractMethod<
    [cohort: AddressLike[], queryType: BigNumberish],
    [string],
    "nonpayable"
  >;

  runEligibilityCheck: TypedContractMethod<
    [patient: AddressLike, maxRiskThreshold: BigNumberish],
    [string],
    "nonpayable"
  >;

  setInsuranceModule: TypedContractMethod<
    [_insuranceModule: AddressLike],
    [void],
    "nonpayable"
  >;

  setResearchRegistry: TypedContractMethod<
    [_researchRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkExists"
  ): TypedContractMethod<[checkId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEligibilityResult"
  ): TypedContractMethod<[checkId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "insuranceModule"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "researchRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "runAggregateQuery"
  ): TypedContractMethod<
    [cohort: AddressLike[], queryType: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "runEligibilityCheck"
  ): TypedContractMethod<
    [patient: AddressLike, maxRiskThreshold: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setInsuranceModule"
  ): TypedContractMethod<[_insuranceModule: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setResearchRegistry"
  ): TypedContractMethod<
    [_researchRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AggregateQueryCompleted"
  ): TypedContractEvent<
    AggregateQueryCompletedEvent.InputTuple,
    AggregateQueryCompletedEvent.OutputTuple,
    AggregateQueryCompletedEvent.OutputObject
  >;
  getEvent(
    key: "EligibilityChecked"
  ): TypedContractEvent<
    EligibilityCheckedEvent.InputTuple,
    EligibilityCheckedEvent.OutputTuple,
    EligibilityCheckedEvent.OutputObject
  >;

  filters: {
    "AggregateQueryCompleted(address,uint8,uint256)": TypedContractEvent<
      AggregateQueryCompletedEvent.InputTuple,
      AggregateQueryCompletedEvent.OutputTuple,
      AggregateQueryCompletedEvent.OutputObject
    >;
    AggregateQueryCompleted: TypedContractEvent<
      AggregateQueryCompletedEvent.InputTuple,
      AggregateQueryCompletedEvent.OutputTuple,
      AggregateQueryCompletedEvent.OutputObject
    >;

    "EligibilityChecked(address,address,bytes32)": TypedContractEvent<
      EligibilityCheckedEvent.InputTuple,
      EligibilityCheckedEvent.OutputTuple,
      EligibilityCheckedEvent.OutputObject
    >;
    EligibilityChecked: TypedContractEvent<
      EligibilityCheckedEvent.InputTuple,
      EligibilityCheckedEvent.OutputTuple,
      EligibilityCheckedEvent.OutputObject
    >;
  };
}
