/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace InsuranceModule {
  export type PolicyStruct = {
    monthlyPremium: BigNumberish;
    coverageAmount: BigNumberish;
    riskThreshold: BigNumberish;
    active: boolean;
  };

  export type PolicyStructOutput = [
    monthlyPremium: bigint,
    coverageAmount: bigint,
    riskThreshold: bigint,
    active: boolean
  ] & {
    monthlyPremium: bigint;
    coverageAmount: bigint;
    riskThreshold: bigint;
    active: boolean;
  };
}

export interface InsuranceModuleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "createPolicy"
      | "getPolicy"
      | "isClaimProcessed"
      | "owner"
      | "paymentVault"
      | "processClaimPayment"
      | "queryEngine"
      | "setPaymentVault"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ClaimProcessed" | "PolicyCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createPolicy",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPolicy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isClaimProcessed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "processClaimPayment",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "queryEngine",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPaymentVault",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPolicy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isClaimProcessed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processClaimPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queryEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPaymentVault",
    data: BytesLike
  ): Result;
}

export namespace ClaimProcessedEvent {
  export type InputTuple = [
    patient: AddressLike,
    checkId: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    patient: string,
    checkId: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    patient: string;
    checkId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyCreatedEvent {
  export type InputTuple = [
    patient: AddressLike,
    premium: BigNumberish,
    coverage: BigNumberish
  ];
  export type OutputTuple = [
    patient: string,
    premium: bigint,
    coverage: bigint
  ];
  export interface OutputObject {
    patient: string;
    premium: bigint;
    coverage: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface InsuranceModule extends BaseContract {
  connect(runner?: ContractRunner | null): InsuranceModule;
  waitForDeployment(): Promise<this>;

  interface: InsuranceModuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createPolicy: TypedContractMethod<
    [
      patient: AddressLike,
      premium: BigNumberish,
      coverage: BigNumberish,
      riskThreshold: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getPolicy: TypedContractMethod<
    [patient: AddressLike],
    [InsuranceModule.PolicyStructOutput],
    "view"
  >;

  isClaimProcessed: TypedContractMethod<
    [checkId: BytesLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  paymentVault: TypedContractMethod<[], [string], "view">;

  processClaimPayment: TypedContractMethod<
    [patient: AddressLike, eligibilityCheckId: BytesLike],
    [void],
    "nonpayable"
  >;

  queryEngine: TypedContractMethod<[], [string], "view">;

  setPaymentVault: TypedContractMethod<
    [_vault: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createPolicy"
  ): TypedContractMethod<
    [
      patient: AddressLike,
      premium: BigNumberish,
      coverage: BigNumberish,
      riskThreshold: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPolicy"
  ): TypedContractMethod<
    [patient: AddressLike],
    [InsuranceModule.PolicyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isClaimProcessed"
  ): TypedContractMethod<[checkId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paymentVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processClaimPayment"
  ): TypedContractMethod<
    [patient: AddressLike, eligibilityCheckId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "queryEngine"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setPaymentVault"
  ): TypedContractMethod<[_vault: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ClaimProcessed"
  ): TypedContractEvent<
    ClaimProcessedEvent.InputTuple,
    ClaimProcessedEvent.OutputTuple,
    ClaimProcessedEvent.OutputObject
  >;
  getEvent(
    key: "PolicyCreated"
  ): TypedContractEvent<
    PolicyCreatedEvent.InputTuple,
    PolicyCreatedEvent.OutputTuple,
    PolicyCreatedEvent.OutputObject
  >;

  filters: {
    "ClaimProcessed(address,bytes32,uint256)": TypedContractEvent<
      ClaimProcessedEvent.InputTuple,
      ClaimProcessedEvent.OutputTuple,
      ClaimProcessedEvent.OutputObject
    >;
    ClaimProcessed: TypedContractEvent<
      ClaimProcessedEvent.InputTuple,
      ClaimProcessedEvent.OutputTuple,
      ClaimProcessedEvent.OutputObject
    >;

    "PolicyCreated(address,uint256,uint256)": TypedContractEvent<
      PolicyCreatedEvent.InputTuple,
      PolicyCreatedEvent.OutputTuple,
      PolicyCreatedEvent.OutputObject
    >;
    PolicyCreated: TypedContractEvent<
      PolicyCreatedEvent.InputTuple,
      PolicyCreatedEvent.OutputTuple,
      PolicyCreatedEvent.OutputObject
    >;
  };
}
