/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MockPaymentVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "RESERVE_UNIT"
      | "confidentialProtocolId"
      | "depositFunds"
      | "getBalance"
      | "getPendingPayment"
      | "insuranceModule"
      | "releasePremium"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "FundsDeposited" | "PremiumReleased"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "RESERVE_UNIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositFunds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingPayment",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "insuranceModule",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "releasePremium",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "RESERVE_UNIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPendingPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "insuranceModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releasePremium",
    data: BytesLike
  ): Result;
}

export namespace FundsDepositedEvent {
  export type InputTuple = [depositor: AddressLike, amount: BigNumberish];
  export type OutputTuple = [depositor: string, amount: bigint];
  export interface OutputObject {
    depositor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PremiumReleasedEvent {
  export type InputTuple = [patient: AddressLike];
  export type OutputTuple = [patient: string];
  export interface OutputObject {
    patient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockPaymentVault extends BaseContract {
  connect(runner?: ContractRunner | null): MockPaymentVault;
  waitForDeployment(): Promise<this>;

  interface: MockPaymentVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  RESERVE_UNIT: TypedContractMethod<[], [bigint], "view">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  depositFunds: TypedContractMethod<[], [void], "payable">;

  getBalance: TypedContractMethod<[], [bigint], "view">;

  getPendingPayment: TypedContractMethod<
    [patient: AddressLike],
    [string],
    "view"
  >;

  insuranceModule: TypedContractMethod<[], [string], "view">;

  releasePremium: TypedContractMethod<
    [to: AddressLike, encAmount: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "RESERVE_UNIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositFunds"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPendingPayment"
  ): TypedContractMethod<[patient: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "insuranceModule"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "releasePremium"
  ): TypedContractMethod<
    [to: AddressLike, encAmount: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "FundsDeposited"
  ): TypedContractEvent<
    FundsDepositedEvent.InputTuple,
    FundsDepositedEvent.OutputTuple,
    FundsDepositedEvent.OutputObject
  >;
  getEvent(
    key: "PremiumReleased"
  ): TypedContractEvent<
    PremiumReleasedEvent.InputTuple,
    PremiumReleasedEvent.OutputTuple,
    PremiumReleasedEvent.OutputObject
  >;

  filters: {
    "FundsDeposited(address,uint256)": TypedContractEvent<
      FundsDepositedEvent.InputTuple,
      FundsDepositedEvent.OutputTuple,
      FundsDepositedEvent.OutputObject
    >;
    FundsDeposited: TypedContractEvent<
      FundsDepositedEvent.InputTuple,
      FundsDepositedEvent.OutputTuple,
      FundsDepositedEvent.OutputObject
    >;

    "PremiumReleased(address)": TypedContractEvent<
      PremiumReleasedEvent.InputTuple,
      PremiumReleasedEvent.OutputTuple,
      PremiumReleasedEvent.OutputObject
    >;
    PremiumReleased: TypedContractEvent<
      PremiumReleasedEvent.InputTuple,
      PremiumReleasedEvent.OutputTuple,
      PremiumReleasedEvent.OutputObject
    >;
  };
}
