/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PatientRegistry {
  export type PatientRecordStruct = {
    riskScore: BytesLike;
    conditionFlags: BytesLike;
    age: BytesLike;
    medCount: BytesLike;
    enrolled: boolean;
    lastUpdated: BigNumberish;
  };

  export type PatientRecordStructOutput = [
    riskScore: string,
    conditionFlags: string,
    age: string,
    medCount: string,
    enrolled: boolean,
    lastUpdated: bigint
  ] & {
    riskScore: string;
    conditionFlags: string;
    age: string;
    medCount: string;
    enrolled: boolean;
    lastUpdated: bigint;
  };
}

export interface PatientRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeProvider"
      | "checkRiskScoreACL"
      | "confidentialProtocolId"
      | "getPatientRecord"
      | "grantDelegatedFieldAccess"
      | "isEnrolled"
      | "providerAuthorized"
      | "queryEngineAddress"
      | "registerPatient"
      | "setQueryEngine"
      | "updateRiskScore"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FieldAccessDelegated"
      | "PatientRegistered"
      | "ProviderAuthorized"
      | "QueryEngineSet"
      | "RiskScoreUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeProvider",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkRiskScoreACL",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPatientRecord",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantDelegatedFieldAccess",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isEnrolled",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "providerAuthorized",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "queryEngineAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerPatient",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setQueryEngine",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRiskScore",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizeProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkRiskScoreACL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPatientRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantDelegatedFieldAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isEnrolled", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "providerAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queryEngineAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerPatient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setQueryEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRiskScore",
    data: BytesLike
  ): Result;
}

export namespace FieldAccessDelegatedEvent {
  export type InputTuple = [
    patient: AddressLike,
    grantee: AddressLike,
    fieldIndex: BigNumberish
  ];
  export type OutputTuple = [
    patient: string,
    grantee: string,
    fieldIndex: bigint
  ];
  export interface OutputObject {
    patient: string;
    grantee: string;
    fieldIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PatientRegisteredEvent {
  export type InputTuple = [patient: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [patient: string, timestamp: bigint];
  export interface OutputObject {
    patient: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProviderAuthorizedEvent {
  export type InputTuple = [patient: AddressLike, provider: AddressLike];
  export type OutputTuple = [patient: string, provider: string];
  export interface OutputObject {
    patient: string;
    provider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QueryEngineSetEvent {
  export type InputTuple = [queryEngine: AddressLike];
  export type OutputTuple = [queryEngine: string];
  export interface OutputObject {
    queryEngine: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskScoreUpdatedEvent {
  export type InputTuple = [patient: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [patient: string, timestamp: bigint];
  export interface OutputObject {
    patient: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PatientRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): PatientRegistry;
  waitForDeployment(): Promise<this>;

  interface: PatientRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeProvider: TypedContractMethod<
    [provider: AddressLike],
    [void],
    "nonpayable"
  >;

  checkRiskScoreACL: TypedContractMethod<
    [patient: AddressLike, grantee: AddressLike],
    [[boolean, boolean] & { contractHasACL: boolean; granteeHasACL: boolean }],
    "view"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getPatientRecord: TypedContractMethod<
    [patient: AddressLike],
    [PatientRegistry.PatientRecordStructOutput],
    "view"
  >;

  grantDelegatedFieldAccess: TypedContractMethod<
    [grantee: AddressLike, fieldIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  isEnrolled: TypedContractMethod<[patient: AddressLike], [boolean], "view">;

  providerAuthorized: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  queryEngineAddress: TypedContractMethod<[], [string], "view">;

  registerPatient: TypedContractMethod<
    [
      _riskScore: BytesLike,
      _riskProof: BytesLike,
      _conditionFlags: BytesLike,
      _flagsProof: BytesLike,
      _age: BytesLike,
      _ageProof: BytesLike,
      _medCount: BytesLike,
      _medProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setQueryEngine: TypedContractMethod<
    [addr: AddressLike],
    [void],
    "nonpayable"
  >;

  updateRiskScore: TypedContractMethod<
    [newScore: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeProvider"
  ): TypedContractMethod<[provider: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkRiskScoreACL"
  ): TypedContractMethod<
    [patient: AddressLike, grantee: AddressLike],
    [[boolean, boolean] & { contractHasACL: boolean; granteeHasACL: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPatientRecord"
  ): TypedContractMethod<
    [patient: AddressLike],
    [PatientRegistry.PatientRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantDelegatedFieldAccess"
  ): TypedContractMethod<
    [grantee: AddressLike, fieldIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isEnrolled"
  ): TypedContractMethod<[patient: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "providerAuthorized"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "queryEngineAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerPatient"
  ): TypedContractMethod<
    [
      _riskScore: BytesLike,
      _riskProof: BytesLike,
      _conditionFlags: BytesLike,
      _flagsProof: BytesLike,
      _age: BytesLike,
      _ageProof: BytesLike,
      _medCount: BytesLike,
      _medProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setQueryEngine"
  ): TypedContractMethod<[addr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateRiskScore"
  ): TypedContractMethod<
    [newScore: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "FieldAccessDelegated"
  ): TypedContractEvent<
    FieldAccessDelegatedEvent.InputTuple,
    FieldAccessDelegatedEvent.OutputTuple,
    FieldAccessDelegatedEvent.OutputObject
  >;
  getEvent(
    key: "PatientRegistered"
  ): TypedContractEvent<
    PatientRegisteredEvent.InputTuple,
    PatientRegisteredEvent.OutputTuple,
    PatientRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ProviderAuthorized"
  ): TypedContractEvent<
    ProviderAuthorizedEvent.InputTuple,
    ProviderAuthorizedEvent.OutputTuple,
    ProviderAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "QueryEngineSet"
  ): TypedContractEvent<
    QueryEngineSetEvent.InputTuple,
    QueryEngineSetEvent.OutputTuple,
    QueryEngineSetEvent.OutputObject
  >;
  getEvent(
    key: "RiskScoreUpdated"
  ): TypedContractEvent<
    RiskScoreUpdatedEvent.InputTuple,
    RiskScoreUpdatedEvent.OutputTuple,
    RiskScoreUpdatedEvent.OutputObject
  >;

  filters: {
    "FieldAccessDelegated(address,address,uint8)": TypedContractEvent<
      FieldAccessDelegatedEvent.InputTuple,
      FieldAccessDelegatedEvent.OutputTuple,
      FieldAccessDelegatedEvent.OutputObject
    >;
    FieldAccessDelegated: TypedContractEvent<
      FieldAccessDelegatedEvent.InputTuple,
      FieldAccessDelegatedEvent.OutputTuple,
      FieldAccessDelegatedEvent.OutputObject
    >;

    "PatientRegistered(address,uint256)": TypedContractEvent<
      PatientRegisteredEvent.InputTuple,
      PatientRegisteredEvent.OutputTuple,
      PatientRegisteredEvent.OutputObject
    >;
    PatientRegistered: TypedContractEvent<
      PatientRegisteredEvent.InputTuple,
      PatientRegisteredEvent.OutputTuple,
      PatientRegisteredEvent.OutputObject
    >;

    "ProviderAuthorized(address,address)": TypedContractEvent<
      ProviderAuthorizedEvent.InputTuple,
      ProviderAuthorizedEvent.OutputTuple,
      ProviderAuthorizedEvent.OutputObject
    >;
    ProviderAuthorized: TypedContractEvent<
      ProviderAuthorizedEvent.InputTuple,
      ProviderAuthorizedEvent.OutputTuple,
      ProviderAuthorizedEvent.OutputObject
    >;

    "QueryEngineSet(address)": TypedContractEvent<
      QueryEngineSetEvent.InputTuple,
      QueryEngineSetEvent.OutputTuple,
      QueryEngineSetEvent.OutputObject
    >;
    QueryEngineSet: TypedContractEvent<
      QueryEngineSetEvent.InputTuple,
      QueryEngineSetEvent.OutputTuple,
      QueryEngineSetEvent.OutputObject
    >;

    "RiskScoreUpdated(address,uint256)": TypedContractEvent<
      RiskScoreUpdatedEvent.InputTuple,
      RiskScoreUpdatedEvent.OutputTuple,
      RiskScoreUpdatedEvent.OutputObject
    >;
    RiskScoreUpdated: TypedContractEvent<
      RiskScoreUpdatedEvent.InputTuple,
      RiskScoreUpdatedEvent.OutputTuple,
      RiskScoreUpdatedEvent.OutputObject
    >;
  };
}
