/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ResearchRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveInstitution"
      | "approvedCohorts"
      | "getCohortCount"
      | "getCohortPatients"
      | "incrementQueryCount"
      | "institutions"
      | "isApproved"
      | "owner"
      | "queryEngine"
      | "registerCohort"
      | "setQueryEngine"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CohortRegistered"
      | "InstitutionApproved"
      | "QueryCountIncremented"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveInstitution",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "approvedCohorts",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCohortCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCohortPatients",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "incrementQueryCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "institutions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isApproved",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "queryEngine",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerCohort",
    values: [AddressLike, BytesLike, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setQueryEngine",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveInstitution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approvedCohorts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCohortCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCohortPatients",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "incrementQueryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "institutions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isApproved", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "queryEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerCohort",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setQueryEngine",
    data: BytesLike
  ): Result;
}

export namespace CohortRegisteredEvent {
  export type InputTuple = [cohortId: BytesLike, patientCount: BigNumberish];
  export type OutputTuple = [cohortId: string, patientCount: bigint];
  export interface OutputObject {
    cohortId: string;
    patientCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InstitutionApprovedEvent {
  export type InputTuple = [institution: AddressLike, name: string];
  export type OutputTuple = [institution: string, name: string];
  export interface OutputObject {
    institution: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QueryCountIncrementedEvent {
  export type InputTuple = [institution: AddressLike, newCount: BigNumberish];
  export type OutputTuple = [institution: string, newCount: bigint];
  export interface OutputObject {
    institution: string;
    newCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ResearchRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ResearchRegistry;
  waitForDeployment(): Promise<this>;

  interface: ResearchRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveInstitution: TypedContractMethod<
    [institution: AddressLike, name: string, purpose: string],
    [void],
    "nonpayable"
  >;

  approvedCohorts: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getCohortCount: TypedContractMethod<
    [institution: AddressLike],
    [bigint],
    "view"
  >;

  getCohortPatients: TypedContractMethod<
    [cohortId: BytesLike],
    [string[]],
    "view"
  >;

  incrementQueryCount: TypedContractMethod<
    [institution: AddressLike],
    [void],
    "nonpayable"
  >;

  institutions: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean, bigint] & {
        name: string;
        purpose: string;
        approved: boolean;
        queryCount: bigint;
      }
    ],
    "view"
  >;

  isApproved: TypedContractMethod<
    [institution: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  queryEngine: TypedContractMethod<[], [string], "view">;

  registerCohort: TypedContractMethod<
    [institution: AddressLike, cohortId: BytesLike, patients: AddressLike[]],
    [void],
    "nonpayable"
  >;

  setQueryEngine: TypedContractMethod<
    [_queryEngine: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveInstitution"
  ): TypedContractMethod<
    [institution: AddressLike, name: string, purpose: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approvedCohorts"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCohortCount"
  ): TypedContractMethod<[institution: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCohortPatients"
  ): TypedContractMethod<[cohortId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "incrementQueryCount"
  ): TypedContractMethod<[institution: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "institutions"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean, bigint] & {
        name: string;
        purpose: string;
        approved: boolean;
        queryCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isApproved"
  ): TypedContractMethod<[institution: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "queryEngine"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerCohort"
  ): TypedContractMethod<
    [institution: AddressLike, cohortId: BytesLike, patients: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setQueryEngine"
  ): TypedContractMethod<[_queryEngine: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CohortRegistered"
  ): TypedContractEvent<
    CohortRegisteredEvent.InputTuple,
    CohortRegisteredEvent.OutputTuple,
    CohortRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "InstitutionApproved"
  ): TypedContractEvent<
    InstitutionApprovedEvent.InputTuple,
    InstitutionApprovedEvent.OutputTuple,
    InstitutionApprovedEvent.OutputObject
  >;
  getEvent(
    key: "QueryCountIncremented"
  ): TypedContractEvent<
    QueryCountIncrementedEvent.InputTuple,
    QueryCountIncrementedEvent.OutputTuple,
    QueryCountIncrementedEvent.OutputObject
  >;

  filters: {
    "CohortRegistered(bytes32,uint256)": TypedContractEvent<
      CohortRegisteredEvent.InputTuple,
      CohortRegisteredEvent.OutputTuple,
      CohortRegisteredEvent.OutputObject
    >;
    CohortRegistered: TypedContractEvent<
      CohortRegisteredEvent.InputTuple,
      CohortRegisteredEvent.OutputTuple,
      CohortRegisteredEvent.OutputObject
    >;

    "InstitutionApproved(address,string)": TypedContractEvent<
      InstitutionApprovedEvent.InputTuple,
      InstitutionApprovedEvent.OutputTuple,
      InstitutionApprovedEvent.OutputObject
    >;
    InstitutionApproved: TypedContractEvent<
      InstitutionApprovedEvent.InputTuple,
      InstitutionApprovedEvent.OutputTuple,
      InstitutionApprovedEvent.OutputObject
    >;

    "QueryCountIncremented(address,uint256)": TypedContractEvent<
      QueryCountIncrementedEvent.InputTuple,
      QueryCountIncrementedEvent.OutputTuple,
      QueryCountIncrementedEvent.OutputObject
    >;
    QueryCountIncremented: TypedContractEvent<
      QueryCountIncrementedEvent.InputTuple,
      QueryCountIncrementedEvent.OutputTuple,
      QueryCountIncrementedEvent.OutputObject
    >;
  };
}
